<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>NouvelleReservation</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2019-10-19T23:40:02</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b3316839-f0c3-40d5-86f7-18d1d750854d</testSuiteGuid>
   <testCaseLink>
      <guid>5bd7c0d3-36fa-4928-880b-657518ce1b24</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OpenTheBrowser</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>010186bb-7b00-4e28-9ae6-d06e6a5530d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73622317-946c-4e96-acc8-4d8cf27ac357</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6166cce-04ab-4fc6-b945-0f305404beec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1a7f81bd-9d41-4a31-ab21-dbeb984587a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NewReservation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b505b81e-65dc-4bc2-b90c-f68f60a1f1bd</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/reservations</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>b505b81e-65dc-4bc2-b90c-f68f60a1f1bd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value> Nom_Client</value>
         <variableId>d420b7dd-e170-4f39-bdea-4fddf414beab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b505b81e-65dc-4bc2-b90c-f68f60a1f1bd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value> Prix</value>
         <variableId>537bf527-b285-47ba-8342-c1d2c1de0ffe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b505b81e-65dc-4bc2-b90c-f68f60a1f1bd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value> Comments</value>
         <variableId>f6dd1db3-f0c9-4987-9dda-efc4a33e1aed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b505b81e-65dc-4bc2-b90c-f68f60a1f1bd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Num_Appartement</value>
         <variableId>f66302f7-87a0-49b9-b3f7-2bbb4d3903ac</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>56f0e072-a83f-4ba5-a211-bb86e513e8df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CloseTheBrowser</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbb76ddc-92fe-48d2-96b8-9f56eef9e5d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb9dcf60-37f8-48ce-8495-476e6dd439f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8f42234-9dae-4c1f-a755-dcc87d1dcb56</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
